### PR TITLE
added new node pool for dev and int

### PR DESCRIPTION
**Pull request by smark88**

### CODE REVIEW

**Review by ddietterich — APPROVED** [review]
lgtm

**Comment by smark88** [comment]
This is going to change the sql since it was manually changed. 

```
# google_sql_database_instance.jade_11_postgres_db[0] will be updated in-place                                                                                                                          
  ~ resource "google_sql_database_instance" "jade_11_postgres_db" {                                                                                                                                       
        connection_name               = "broad-jade-dev:us-central1:jade-postgres-11-8a00fd4d3b"                                                                                                          
        database_version              = "POSTGRES_11"                                                                                                                                                     
        first_ip_address              = "10.12.0.13"                                                                                                                                                      
        id                            = "jade-postgres-11-8a00fd4d3b"                                                                                                                                     
        ip_address                    = [                                                                                                                                                                 
            {                                                                                                                                                                                             
                ip_address     = "10.12.0.13"                                                                                                                                                             
                time_to_retire = ""                                                                                                                                                                       
                type           = "PRIVATE"                                                                                                                                                                
            },                                                                                                                                                                                            
        ]                                                                                                                                                                                                 
        name                          = "jade-postgres-11-8a00fd4d3b"                                                                                                                                     
        private_ip_address            = "10.12.0.13"                                                                                                                                                      
        project                       = "broad-jade-dev"                                                                                                                                                  
        region                        = "us-central1"                                                                                                                                                     
        self_link                     = "https://sqladmin.googleapis.com/sql/v1beta4/projects/broad-jade-dev/instances/jade-postgres-11-8a00fd4d3b"                                                       
        server_ca_cert                = [                                                                                                                                                                 
            {                                                                                                                                                                                             
                cert             = <<~EOT                                                                                                                                                                 
                    -----BEGIN CERTIFICATE-----                                                                                                                                                           
                    MIIDfzCCAmegAwIBAgIBADANBgkqhkiG9w0BAQsFADB3MS0wKwYDVQQuEyRjMjIx                                                                                                                      
                    Y2UwOS05NzNiLTQ1MGItYmI0Yy1lYmJkZmI4YTc4NGUxIzAhBgNVBAMTGkdvb2ds                                                                                                                      
                    ZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkG                                                                                                                      
                    A1UEBhMCVVMwHhcNMjAwNDE0MTk0MjU5WhcNMzAwNDEyMTk0MzU5WjB3MS0wKwYD                                                                                                                      
                    VQQuEyRjMjIxY2UwOS05NzNiLTQ1MGItYmI0Yy1lYmJkZmI4YTc4NGUxIzAhBgNV                                                                                                                      
                    BAMTGkdvb2dsZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUs                                                                                                                      
                    IEluYzELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB                                                                                                                      
                    AQCRkndhC8G6bSdxaIpAXEgRuogwTS/cMOtWFyuqTT/GGzrsCyUtMiZtcUpCu61U                                                                                                                      
                    RX/ugjLWKY7XD9LNBZIaY+bCw5zpNDLjste/DtEJK+BFCW31mQh1qOM8vFqZLCyN                                                                                                                      
                    djN/QdIlWjqwEyUlJWDo+j/AkFgWlzCrtLI1F7NMWwL5imkAt9p4weCuSv8ZpIHb                                                                                                                      
                    ign676yNiTQd7pjmrYzYRrQmqZNdUv3EONVBVg2WkUz66uiB8TAgT2jULQvwmoUX                                                                                                                      
                    PGm5JiyypHz9K2F1ZxAREi4M6i1nxRJd8CnMHLNsrt65D2VLiDaAZT31bryK+FGj                                                                                                                      
                    ePC7hHz1364MumjUa9pT8T91AgMBAAGjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQAw                                                                                                                      
                    DQYJKoZIhvcNAQELBQADggEBAISVeSRUlQkSVzluMPa+uwBUGhJQmv+x4t8Y5F3x                                                                                                                      
                    Wm95pK54xx5QC7VYpi3Co9WiJK07Cl8SO66O77TXmFmvH3XcYN7kNXWpWXByReOW                                                                                                                      
                    oEZAm+n5eI9CuQbJZuoG0YVnHvhMm0VQfk/5c6yfH7A7lr3tCnn6349Qi/ZIXZHd                                                                                                                      
                    9gvpNO4F/luB8gJN7cDjICz7fLmi6TAc1pbheoNaWFV7A6AQOWyPBK6N+5i2g36p                                                                                                                      
                    GkymO6PbkEdYsCWo/3EhgK9sa74KXa591YizDCy3BnzcVThpXSiAP52E+tyx2tGA                                                                                                                      
                    MAEXIQR6pSc7m3ZXD5JSWdfngFPIXmsDNA4YuK66eFQopvI=                                                                                                                                      
                    -----END CERTIFICATE-----                                                                                                                                                             
                EOT                                                                                                                                                                                       
                common_name      = "C=US,O=Google\\, Inc,CN=Google Cloud SQL Server CA,dnQualifier=c221ce09-973b-450b-bb4c-ebbdfb8a784e"                                                                  
                create_time      = "2020-04-14T19:42:59.974Z"
                expiration_time  = "2030-04-12T19:43:59.974Z"
                sha1_fingerprint = "72dfce00136d70a4f840ba6973a438e6b4509842"
            },
        ]
        service_account_email_address = "p970791974390-7f5mya@gcp-sa-cloud-sql.iam.gserviceaccount.com"

      ~ settings {
            activation_policy           = "ALWAYS"
            authorized_gae_applications = []
            availability_type           = "ZONAL"
            crash_safe_replication      = false
            disk_autoresize             = true
            disk_size                   = 15
            disk_type                   = "PD_SSD"
            pricing_plan                = "PER_USE"
            replication_type            = "SYNCHRONOUS"
          ~ tier                        = "db-custom-2-7680" -> "db-g1-small"
            user_labels                 = {
                "app"   = "jade"
              "role"  = "database"                                                                                                                                                            [155/1880]
                "state" = "active"
            }
            version                     = 27

          ~ backup_configuration {
                binary_log_enabled = false
                enabled            = true
              - location           = "us" -> null
                start_time         = "06:00"
            }

          ~ database_flags {
              ~ name  = "log_connections" -> "max_connections"
              ~ value = "on" -> "1024"
            }
          - database_flags {
              - name  = "log_disconnections" -> null
              - value = "on" -> null
            }
          - database_flags {
              - name  = "log_lock_waits" -> null
              - value = "on" -> null
            }
          - database_flags {
              - name  = "log_statement" -> null
              - value = "all" -> null
            }

            ip_configuration {
                ipv4_enabled    = false
                private_network = "projects/broad-jade-dev/global/networks/dev-network"
                require_ssl     = true

                authorized_networks {
                    name  = "Broad"
                    value = "69.173.64.0/18"
                }
                authorized_networks {
                    name  = "kubernetes"
                    value = "130.211.17.99"
                }
            }

            location_preference {
                zone = "us-central1-c"
            }

          - maintenance_window {
              - day  = 0 -> null
              - hour = 0 -> null
            }
        }
    }

# module.k8s-nodes-2.google_container_node_pool.pool will be created
  + resource "google_container_node_pool" "pool" {
      + cluster             = "dev-master"
      + id                  = (known after apply)
      + initial_node_count  = (known after apply)
      + instance_group_urls = (known after apply)
      + location            = "us-central1"
      + max_pods_per_node   = (known after apply)
      + name                = "dev-node-2"
      + name_prefix         = (known after apply)
      + node_count          = 1
      + node_locations      = (known after apply)
      + project             = (known after apply)
      + region              = (known after apply)
      + version             = (known after apply)
      + zone                = (known after apply)

      + management {
          + auto_repair  = true
          + auto_upgrade = true
        }

      + node_config {
          + disk_size_gb      = 50
          + disk_type         = (known after apply)
          + guest_accelerator = (known after apply)
          + image_type        = "COS"
          + labels            = {
              + "environment" = "dev"
              + "project"     = "jade"
            }
          + local_ssd_count   = (known after apply)
          + machine_type      = "n1-standard-2"
          + metadata          = {
              + "disable-legacy-endpoints"         = "true"
              + "google-compute-enable-virtio-rng" = "false"
            }
          + oauth_scopes      = [
              + "https://www.googleapis.com/auth/compute",
              + "https://www.googleapis.com/auth/devstorage.read_only",
              + "https://www.googleapis.com/auth/logging.write",
              + "https://www.googleapis.com/auth/monitoring",
            ]
          + preemptible       = false
          + service_account   = (known after apply)
          + tags              = [
              + "jade",
              + "dev",
              + "kubernetes",
            ]
          + taint             = (known after apply)

          + shielded_instance_config {
              + enable_integrity_monitoring = (known after apply)
              + enable_secure_boot          = (known after apply)
            }

          + workload_metadata_config {
              + node_metadata = "GKE_METADATA_SERVER"
            }
        }

      + upgrade_settings {
          + max_surge       = (known after apply)
          + max_unavailable = (known after apply)
        }
    }
```

**Comment by smark88** [comment]
new plan 

```
# google_sql_database_instance.jade_11_postgres_db[0] will be updated in-place                                                                                                                          
  ~ resource "google_sql_database_instance" "jade_11_postgres_db" {                                                                                                                                       
        connection_name               = "broad-jade-dev:us-central1:jade-postgres-11-8a00fd4d3b"                                                                                                          
        database_version              = "POSTGRES_11"                                                                                                                                                     
        first_ip_address              = "10.12.0.13"                                                                                                                                                      
        id                            = "jade-postgres-11-8a00fd4d3b"                                                                                                                                     
        ip_address                    = [                                                                                                                                                                 
            {                                                                                                                                                                                             
                ip_address     = "10.12.0.13"                                                                                                                                                             
                time_to_retire = ""                                                                                                                                                                       
                type           = "PRIVATE"                                                                                                                                                                
            },                                                                                                                                                                                            
        ]                                                                                                                                                                                                 
        name                          = "jade-postgres-11-8a00fd4d3b"                                                                                                                                     
        private_ip_address            = "10.12.0.13"                                                                                                                                                      
        project                       = "broad-jade-dev"                                                                                                                                                  
        region                        = "us-central1"                                                                                                                                                     
        self_link                     = "https://sqladmin.googleapis.com/sql/v1beta4/projects/broad-jade-dev/instances/jade-postgres-11-8a00fd4d3b"                                                       
        server_ca_cert                = [                                                                                                                                                                 
            {                                                                                                                                                                                             
                cert             = <<~EOT                                                                                                                                                                 
                    -----BEGIN CERTIFICATE-----                                                                                                                                                           
                    MIIDfzCCAmegAwIBAgIBADANBgkqhkiG9w0BAQsFADB3MS0wKwYDVQQuEyRjMjIx                                                                                                                      
                    Y2UwOS05NzNiLTQ1MGItYmI0Yy1lYmJkZmI4YTc4NGUxIzAhBgNVBAMTGkdvb2ds                                                                                                                      
                    ZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkG                                                                                                                      
                    A1UEBhMCVVMwHhcNMjAwNDE0MTk0MjU5WhcNMzAwNDEyMTk0MzU5WjB3MS0wKwYD                                                                                                                      
                    VQQuEyRjMjIxY2UwOS05NzNiLTQ1MGItYmI0Yy1lYmJkZmI4YTc4NGUxIzAhBgNV                                                                                                                      
                    BAMTGkdvb2dsZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUs                                                                                                                      
                    IEluYzELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB                                                                                                                      
                    AQCRkndhC8G6bSdxaIpAXEgRuogwTS/cMOtWFyuqTT/GGzrsCyUtMiZtcUpCu61U                                                                                                                      
                    RX/ugjLWKY7XD9LNBZIaY+bCw5zpNDLjste/DtEJK+BFCW31mQh1qOM8vFqZLCyN                                                                                                                      
                    djN/QdIlWjqwEyUlJWDo+j/AkFgWlzCrtLI1F7NMWwL5imkAt9p4weCuSv8ZpIHb                                                                                                                      
                    ign676yNiTQd7pjmrYzYRrQmqZNdUv3EONVBVg2WkUz66uiB8TAgT2jULQvwmoUX                                                                                                                      
                    PGm5JiyypHz9K2F1ZxAREi4M6i1nxRJd8CnMHLNsrt65D2VLiDaAZT31bryK+FGj                                                                                                                      
                    ePC7hHz1364MumjUa9pT8T91AgMBAAGjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQAw                                                                                                                      
                    DQYJKoZIhvcNAQELBQADggEBAISVeSRUlQkSVzluMPa+uwBUGhJQmv+x4t8Y5F3x                                                                                                                      
                    Wm95pK54xx5QC7VYpi3Co9WiJK07Cl8SO66O77TXmFmvH3XcYN7kNXWpWXByReOW                                                                                                                      
                    oEZAm+n5eI9CuQbJZuoG0YVnHvhMm0VQfk/5c6yfH7A7lr3tCnn6349Qi/ZIXZHd                                                                                                                      
                    9gvpNO4F/luB8gJN7cDjICz7fLmi6TAc1pbheoNaWFV7A6AQOWyPBK6N+5i2g36p                                                                                                                      
                    GkymO6PbkEdYsCWo/3EhgK9sa74KXa591YizDCy3BnzcVThpXSiAP52E+tyx2tGA                                                                                                                      
                    MAEXIQR6pSc7m3ZXD5JSWdfngFPIXmsDNA4YuK66eFQopvI=                                                                                                                                      
                    -----END CERTIFICATE-----                                                                                                                                                             
                EOT                                                                                                                                                                                       
                common_name      = "C=US,O=Google\\, Inc,CN=Google Cloud SQL Server CA,dnQualifier=c221ce09-973b-450b-bb4c-ebbdfb8a784e"                                                                  
                create_time      = "2020-04-14T19:42:59.974Z"                                                                                                                                             
                expiration_time  = "2030-04-12T19:43:59.974Z"                                                                                                                                             
                sha1_fingerprint = "72dfce00136d70a4f840ba6973a438e6b4509842"                                                                                                                             
            },                                                                                                                                                                                            
        ]                                                                                                                                                                                                 
        service_account_email_address = "p970791974390-7f5mya@gcp-sa-cloud-sql.iam.gserviceaccount.com"                                                                                                   
                                                                                                                                                                                                          
      ~ settings {                                                                                                                                                                                        
            activation_policy           = "ALWAYS"                                                                                                                                                        
            authorized_gae_applications = []                                                                                                                                                              
            availability_type           = "ZONAL"                                                                                                                                                         
            crash_safe_replication      = false                                                                                                                                                           
            disk_autoresize             = true                                                                                                                                                            
            disk_size                   = 15                                                                                                                                                              
            disk_type                   = "PD_SSD"                                                                                                                                                        
            pricing_plan                = "PER_USE"                                                                                                                                                       
            replication_type            = "SYNCHRONOUS"                                                                                                                                                   
          ~ tier                        = "db-custom-2-7680" -> "db-n1-standard-2"             
           user_labels                 = {
                "app"   = "jade"
                "role"  = "database"
                "state" = "active"
            }
            version                     = 27

            backup_configuration {
                binary_log_enabled = false
                enabled            = true
                location           = "us"
                start_time         = "06:00"
            }

            database_flags {
                name  = "log_connections"
                value = "on"
            }
            database_flags {
                name  = "log_disconnections"
                value = "on"
            }
            database_flags {
                name  = "log_lock_waits"
                value = "on"
            }
            database_flags {
                name  = "log_statement"
                value = "all"
            }

            ip_configuration {
                ipv4_enabled    = false
                private_network = "projects/broad-jade-dev/global/networks/dev-network"
                require_ssl     = true

                authorized_networks {
                    name  = "Broad"
                    value = "69.173.64.0/18"
                }
                authorized_networks {
                    name  = "kubernetes"
                    value = "130.211.17.99"
                }
            }

            location_preference {
                zone = "us-central1-c"
            }

          - maintenance_window {
              - day  = 0 -> null
              - hour = 0 -> null
            }
        }
    }
 # module.k8s-nodes-2.google_container_node_pool.pool will be created
  + resource "google_container_node_pool" "pool" {
      + cluster             = "dev-master"
      + id                  = (known after apply)
      + initial_node_count  = (known after apply)
      + instance_group_urls = (known after apply)
      + location            = "us-central1"
      + max_pods_per_node   = (known after apply)
      + name                = "dev-node-2"
      + name_prefix         = (known after apply)
      + node_count          = 1
      + node_locations      = (known after apply)
      + project             = (known after apply)
      + region              = (known after apply)
      + version             = (known after apply)
      + zone                = (known after apply)

      + management {
          + auto_repair  = true
          + auto_upgrade = true
        }

      + node_config {
          + disk_size_gb      = 50
          + disk_type         = (known after apply)
          + guest_accelerator = (known after apply)
          + image_type        = "COS"
          + labels            = {
              + "environment" = "dev"
              + "project"     = "jade"
            }
          + local_ssd_count   = (known after apply)
          + machine_type      = "n1-standard-2"
          + metadata          = {
              + "disable-legacy-endpoints"         = "true"
              + "google-compute-enable-virtio-rng" = "false"
            }
          + oauth_scopes      = [
              + "https://www.googleapis.com/auth/compute",
              + "https://www.googleapis.com/auth/devstorage.read_only",
              + "https://www.googleapis.com/auth/logging.write",
              + "https://www.googleapis.com/auth/monitoring",
            ]
          + preemptible       = false
          + service_account   = (known after apply)
          + tags              = [
              + "jade",
              + "dev",
              + "kubernetes",
            ]
          + taint             = (known after apply)

          + shielded_instance_config {
              + enable_integrity_monitoring = (known after apply)
              + enable_secure_boot          = (known after apply)
            }

          + workload_metadata_config {
              + node_metadata = "GKE_METADATA_SERVER"
            }
        }

      + upgrade_settings {
          + max_surge       = (known after apply)
          + max_unavailable = (known after apply)
        }
    }

```

**Review by ddietterich — APPROVED** [review]
Looks even better

**Pull request merged**
