### PR TITLE
[DCJ-576] Codify doubled Prod DB resource allocation

### PR DESCRIPTION
**Pull request by okotsopoulos**
https://broadworkbench.atlassian.net/browse/DCJ-576

During our last prod incident, we manually modified TDR Prod DB's resource allocation in the GCP console:

- vCPUs 4 → 8
- memory 15GB → 32GB

This change codifies and documents that manual increase (even though TDR's Terraform is not currently applicable).

Relevant documentation: https://cloud.google.com/sql/docs/mysql/instance-settings
```
Legacy machine type	vCPUs	Memory (MBs)	db-custom-CPU-RAM string (API tier string)
db-n1-standard-1	1	3840	db-custom-1-3840
db-n1-standard-2	2	7680	db-custom-2-7680
db-n1-standard-4	4	15360	db-custom-4-15360
db-n1-standard-8	8	30720	db-custom-8-30720
```

**Notes for Reviewers**

1. When merged, this PR will *not* auto-apply Terraform changes: see https://github.com/broadinstitute/terraform-jade/pull/158 for more context.
2. I suspect the failed Staging plan is a result of TDR Staging being completely off Vault and onto GSM.  At any rate, the failure is not related to this PR.

### CODE REVIEW

**Review by rushtong — APPROVED** [review]
👍🏽

**Comment by ungwudik** [comment]
@okotsopoulos I'm doing compliance review. Looks like `staging Terraform Plan` failed. Is that not a blocker for releasing this change to staging?

**Comment by ungwudik** [comment]
> @okotsopoulos I'm doing compliance review. Looks like `staging Terraform Plan` failed. Is that not a blocker for releasing this change to staging?

Looks like this ticket is a documentation only change (going from the Security Impact Description).

**Comment by okotsopoulos** [comment]
@ungwudik exactly -- TDR Terraform repo is functioning as documentation with changes not applied, and even so this was a prod-only change.

**Pull request merged**
