### PR TITLE
Add test runner SA to all envs

### PR DESCRIPTION
**Pull request by fboulnois**
Make the test runner service account to all environments

### CODE REVIEW

**Review by snf2ye — APPROVED** [review]

**Comment by smark88** [comment]
Please write key to vault https://github.com/broadinstitute/terraform-jade/blob/4c5ce95ce9267edb1134903c76f62d06c54fe0d5/modules/datarepo-app/serviceaccounts.tf#L94-L106

**Comment by smark88** [comment]
Also nothing in the plan suggests these changes in the code.

**Comment by smark88** [comment]
> Also nothing in the plan suggests these changes in the code.

https://github.com/broadinstitute/terraform-jade/blob/fb-DR-1333-test-runner-sa/environments/alpha/main.tf#L51

Changing the ref to the branch would show the changes in the plan and then back to master on merge.

**Review by smark88 — CHANGES_REQUESTED** [review]
change ref for app plan and add vault secret

**Review by smark88 — APPROVED** [review]
LGTM please revert to master for refs. 👍

**Pull request merged**
